add new layouts
Sheps29/layouts pull request #1
Opened 2024-04-28 11:59 UTC by Sheps29

00001

2024-04-28 12:47 UTC, PavelPavells requested changes

2024-04-28 12:47 UTC, PavelPavells commented on fluffy.jpg
добавить отдельную папку под изображение
-> images/fluffy.jpg

2024-04-28 12:47 UTC, PavelPavells commented on layout1.html
> +        </head>
сместить влево тэг

2024-04-28 12:47 UTC, PavelPavells commented on layout1.html
> +        <div>
div лишний

2024-04-28 12:47 UTC, PavelPavells commented on layout1.html
> +                <li>Introductory</li>
каждый элемент должен содержать ссылки

2024-04-28 12:47 UTC, PavelPavells commented on layout1.html
> +        <div>
div лишний

2024-04-28 12:47 UTC, PavelPavells commented on layout1.html
> +    <footer>
нужно перенести в main тэг

2024-04-28 12:47 UTC, PavelPavells commented on Layout2.html
> +         <p>The cat, with eyne of burning coal, Now crouches from (before) the mouse's hole.</p>
заменить на -> blockquote

2024-04-28 12:47 UTC, PavelPavells commented on Layout2.html
> +        <div>
лишний div

2024-04-28 12:47 UTC, PavelPavells commented on Layout2.html
> +        <div>
лишний div

2024-04-28 12:47 UTC, PavelPavells commented on Layout3.html
> +        <div>
лишний div

2024-04-28 12:47 UTC, PavelPavells commented on Layout3.html
> +                   <li>Introductory</li>
это будут ссылки

2024-04-28 12:47 UTC, PavelPavells commented on Layout3.html
> +        <div>
лишний div

2024-04-28 12:47 UTC, PavelPavells commented on Layout3.html
> +            <img src="fluffy.jpg" alt="кот">
src="./images/fluffy.jpg"

2024-04-28 12:47 UTC, PavelPavells commented on Layout3.html
> +            <img src="fluffy.jpg" alt="кот">
alt="Cat"

2024-04-28 12:47 UTC, PavelPavells commented on Layout3.html
> +            <p>The cat, with eyne of burning coal, Now crouches from (before) the mouse's hole.</p>
blockquote

2024-04-28 12:47 UTC, PavelPavells commented on layout5.html
> +        <div>
лишний div

2024-04-28 12:47 UTC, PavelPavells commented on layout5.html
> +        <div>
лишний div

2024-04-28 12:47 UTC, PavelPavells commented on layout9.html
> +        <div>
div не нужен

2024-04-28 12:47 UTC, PavelPavells commented on layout9.html
> +        <div>
div лишний

2024-04-28 12:47 UTC, PavelPavells commented on layout9.html
> +           <ul>
обернуть в nav

2024-04-28 12:47 UTC, PavelPavells commented on layout9.html
> +            <li>The Dawn of Aeronautics</li>
каждый li это ссылка

2024-04-28 12:47 UTC, PavelPavells commented on layout9.html
> +        <div>
лишний div

2024-04-28 12:47 UTC, PavelPavells commented on layout9.html
> +           <p>Following his own account, Lunardi's first act on finding himself fairly above the town was to fortify himself with some glasses of wine, and to devour the leg of a chicken. He describe
p -> article

2024-04-28 12:47 UTC, PavelPavells commented on layout9.html
> +        <p>This book is available to read in full on the Project Gutenburg website.</p>
Должна быть ссылка как в макете

2024-04-28 13:01 UTC, Sheps29 commented on Layout3.html
> +        <div>
исправлено

2024-04-28 13:01 UTC, Sheps29 commented on Layout3.html
> +                   <li>Introductory</li>
исправлено

2024-04-28 13:01 UTC, Sheps29 commented on Layout3.html
> +        <div>
исправлено

2024-04-28 13:01 UTC, Sheps29 commented on Layout3.html
> +            <img src="fluffy.jpg" alt="кот">
исправлено

2024-04-28 13:01 UTC, Sheps29 commented on Layout3.html
> +            <img src="fluffy.jpg" alt="кот">
исправлено

2024-04-28 13:01 UTC, Sheps29 commented on Layout3.html
> +            <p>The cat, with eyne of burning coal, Now crouches from (before) the mouse's hole.</p>
исправлено

2024-04-28 13:02 UTC, Sheps29 commented on fluffy.jpg
исправлено

2024-06-01 21:09 UTC, PavelPavells requested changes

2024-06-01 21:09 UTC, PavelPavells commented on Layout2.html
> +	<link rel="stylesheet" href="reset2.css">
файлы со стилями нужно вынести в отдельную директторию styles/**

2024-06-01 21:09 UTC, PavelPavells commented on Layout2.html
> +
что-то не то с форматированием

2024-06-01 21:09 UTC, PavelPavells commented on Layout3.html
> +<!DOCTYPE html>
форматирование

2024-06-01 21:09 UTC, PavelPavells commented on domus.html
> +        <img src="" alt="">
почему src пустое? alt не должен быто пустым

2024-06-01 21:09 UTC, PavelPavells commented on domus.html
> +        <img src="" alt="">
тоже самое

2024-06-01 21:09 UTC, PavelPavells commented on domus.html
> +        <img src="" alt="">
тоже самое и ниже тоже

2024-06-01 21:09 UTC, PavelPavells commented on images/cat-mem.jpg
картинки необходимо хранить в png формате

2024-06-01 21:09 UTC, PavelPavells commented on layout1.html
> +  <link rel="stylesheet" href="reset.css">
в отдельную директорию styles/**

2024-06-01 21:09 UTC, PavelPavells commented on layout5.html
> +				<aside class="left">
нейминг не совсем очевидный

2024-06-01 21:09 UTC, PavelPavells commented on style-domus.css
> +  display: flex;
это не критично но нужно соблюдать некие правила
Сначала иду важные свойство по типу display, position, width, height etc.
Затем идут margin, padding, border
Затем все свойства связанные с текстами по типу font-size, font-weight etc

Это нужно поправить во всех файлах .css

2024-06-01 21:09 UTC, PavelPavells commented on style-domus.css
> +.section_one p:nth-child(1) {
::first-child??

2024-06-01 21:09 UTC, PavelPavells commented on style-domus.css
> +  margin: 30px 500px 20px 500px;
Таких огромных маржинов быть не должно их лучше избегать и думать над другим решением

2024-06-01 21:09 UTC, PavelPavells commented on style3.css
> +	text-align: justify;
Опасное свойство может не работать в некоторых бразуерах
Есть сайт - caniuse, там собрные все свйоства css и их совместимость в бразуерах

2024-06-01 21:09 UTC, PavelPavells commented on style3.css
> +	display: inline-block;
В чем профит использовать inline-block?

2024-06-01 21:09 UTC, PavelPavells commented on style3.css
> +	right: 100%;
left: 0?

2024-06-01 21:09 UTC, PavelPavells commented on style3.css
> +	border-style: solid;
Выглядит как что-то скопипащенное откуда-то)))
Можно жеж в одну строку
border: 5px solid .....

2024-06-01 21:09 UTC, PavelPavells commented on style5.css
> +.left~aside {
nice

2024-06-01 21:09 UTC, PavelPavells commented on style9.css
> +		max-height: 25%;
Спорное решение
Для чего так?

2024-06-15 12:30 UTC, PavelPavells approved these changes

2024-06-15 12:33 UTC, merged